---
title: "About"
format:
    html:
        toc: true
---

**Forester by Education, Technologist by Interest, Nature Lover by Heart**

I work as a forest scientist in the field of remote sensing and geospatial data analysis. Leveraging cutting-edge tools and technologies to integrate all kinds of spatial information for an in-depth analysis and advanced visualizations. 

I am passionate about maps of all kinds and have recently developed a keen interest in Lidar data. Whenever possible, I advocate for the use of free and open-source software (FOSS) solutions, using RStats extensively and encouraging my colleagues to support and adopt FOSS.

I firmly believe that digital technologies hold immense potential to revolutionize our approach to environmental management and conservation.

I aim to contribute to a greener future.


### Professional Experience

{{< include /content/about/_jobs.qmd >}}


### Presentations

#### Presenter

{{< include /content/about/_presentations_presenter.qmd >}}


#### Co-Presenter

{{< include /content/about/_presentations_copresenter.qmd >}}

### Publications

{{< include /content/about/_publications.qmd >}}

### Attended Conferences / Workshops

{{< include /content/about/_attended.qmd >}}


--- 

##### ([deutsche Version](/content/about/about_de.html))
